name: my first workflow
on: push
job:
  first job:
     runs-on: ubuntu-latest
     steps:
     - name: checkout repo
       uses: actions/checkout@v5
     - name: welcome messgae
       run: echo "my first github action job"
     - name: list files
       run: li
     - name: read files
       run: cat README.md